### ISSUE TITLE
Game crashes on multiplayer join menu

### ISSUE THREAD

**Issue by actinium-225** [xzxADIxzx/Scheme-Size#52]
im on steam version btw

**Comment by xzxADIxzx** [comment]
Did you update Mindustry to v144?
Did you update the mod to 2.7.65?
Crash log?

**Comment by actinium-225** [comment]
its on v144 and im using the newest release of the mod but ill get the crash file rq

**Comment by actinium-225** [comment]
> Mindustry has crashed. How unfortunate.
Version: steam build 144.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2008mb
Cores: 8
Mods: auto-drill:1, schematics-pack:9, scheme-size:2.7.54, schemepack:1, time-control:0.2, useful-scripts-and-logic-schematics:beta 1

java.lang.ClassCastException: class arc.scene.ui.layout.Stack cannot be cast to class arc.scene.ui.layout.Table (arc.scene.ui.layout.Stack and arc.scene.ui.layout.Table are in unnamed module of loader java.net.URLClassLoader @4ccabbaa)
	at scheme.ui.dialogs.JoinViaClajDialog.fixJoinDialog(JoinViaClajDialog.java:77)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:397)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Dialog.show(Dialog.java:468)
	at arc.scene.ui.Dialog.show(Dialog.java:507)
	at arc.scene.ui.Dialog.show(Dialog.java:502)
	at mindustry.ui.fragments.MenuFragment.checkPlay(MenuFragment.java:220)
	at mindustry.ui.fragments.MenuFragment.lambda$buildDesktop$24(MenuFragment.java:190)
	at mindustry.ui.fragments.MenuFragment.lambda$buttons$32(MenuFragment.java:261)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by actinium-225** [comment]
btw it only crashes when i click the join button

**Comment by xzxADIxzx** [comment]
2.7.54 isn't the newest version of the mod, please update to 2.7.65

**Comment by xzxADIxzx** [comment]
Hope you updated the mod
