### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Artiks-Nasik** [xzxADIxzx/Scheme-Size#56]
crashing at loading game. game build 144
crash log:```java
Version: release build 144
(Foo's Client Version: 5d9eb5f, May. 12, 2023 Unstable)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 10 x32 (x86)
Java Version: 1.8.0_351
Runtime Available Memory: 247mb
Cores: 12
Mods: scheme-size:2.7.65

java.lang.RuntimeException: Error loading mod scheme-size
	at mindustry.mod.Mods.contextRun(Mods.java:848)
	at mindustry.mod.Mods.lambda$eachClass$32(Mods.java:836)
	at arc.struct.Seq.each(Seq.java:182)
	at mindustry.mod.Mods.eachClass(Mods.java:836)
	at mindustry.ClientLauncher.update(ClientLauncher.java:239)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
Caused by: arc.util.ArcRuntimeException: java.io.FileNotFoundException: C:\Users\miral\AppData\Roaming\Mindustry\mods\xzxadixzxscheme-size.zip (access denied)
	at arc.files.ZipFi.<init>(ZipFi.java:70)
	at scheme.SchemeUpdater.load(SchemeUpdater.java:30)
	at scheme.Main.init(Main.java:48)
	at mindustry.mod.Mods.lambda$eachClass$31(Mods.java:836)
	at mindustry.mod.Mods.contextRun(Mods.java:846)
	... 8 more
Caused by: java.io.FileNotFoundException: C:\Users\miral\AppData\Roaming\Mindustry\mods\xzxadixzxscheme-size.zip (access denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at arc.files.ZipFi.<init>(ZipFi.java:27)
	... 12 more
```

**Comment by xzxADIxzx** [comment]
Hm, mod cannot find mod's file, but idk why 😞
